language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install unittest2
  - pip install coverage
script:
  - sh -c 'cd ./tests/ && coverage run -m --source=app unittest discover test && coverage report'
after_success:
  - coveralls
