language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install unittest2
  - pip install coverage
script:
  - nosetests --with-coverage --cover-erase --cover-package=tests
after_success:
  - coveralls
